# Flutter build
variables:
  projectDirectory: 'knab_Flutter'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: my-release-key.keystore
        apksignerKeystorePassword: $(keypassword)
        apksignerKeystoreAlias: $(key)
        apksignerKeyPassword: $(keypassword)
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1

    # Distribute the app
    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'AppCenter'
        appSlug: '$(APP_CENTER_SLUG)'
        appFile: '$(APP_FILE)' # Relative path from the repo root to the APK or IPA file you want to publish
        symbolsOption: 'Android'
        releaseNotesOption: 'input'
        releaseNotesInput: 'Here are the release notes for this version.'
        destinationType: 'groups'