name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #CI/CD
  appcenter: ^0.2.1
  appcenter_crashes: ^0.2.1
  appcenter_analytics: ^0.2.1

  
  flutter:
    sdk: flutter
  
  #Local database
  moor: ^4.2.0
  sqlite3_flutter_libs: ^0.4.1
  path_provider: ^2.0.1
  path: ^1.8.0

  #uuid generator
  uuid: ^3.0.1
  
  #Service locator
  get_it: ^6.0.0

  #Bloc for state management
  bloc: ^6.0.2
  flutter_bloc: ^6.0.2

  #Value equality
  equatable: ^1.2.0

  #Functional programming thingies
  dartz: ^0.8.6

  #Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2

  #Local cache
  shared_preferences: ^0.5.3+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

  moor_generator: ^4.2.0

  build_runner: ^1.12.2


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
